import React, { useState } from 'react';
import { AIContentDetector, AIDetectionResult } from '../utils/aiContentDetection';
import { Bot, AlertTriangle, CheckCircle, Brain, BarChart3, FileText } from 'lucide-react';
import { Bar, Doughnut } from 'react-chartjs-2';

const AIDetection: React.FC = () => {
  const [text, setText] = useState('');
  const [result, setResult] = useState<AIDetectionResult | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [detector] = useState(() => new AIContentDetector());

  const analyzeText = async () => {
    if (!text.trim()) return;
    
    setIsAnalyzing(true);
    
    // Simulate processing time for better UX
    setTimeout(() => {
      const analysisResult = detector.analyzeText(text);
      setResult(analysisResult);
      setIsAnalyzing(false);
    }, 1500);
  };

  const getResultColor = (isAI: boolean, confidence: number) => {
    if (isAI && confidence > 0.8) return 'text-red-700 bg-red-100';
    if (isAI) return 'text-orange-700 bg-orange-100';
    return 'text-green-700 bg-green-100';
  };

  const getResultIcon = (isAI: boolean) => {
    return isAI ? 
      <AlertTriangle className="w-6 h-6 text-red-500" /> : 
      <CheckCircle className="w-6 h-6 text-green-500" />;
  };

  // Chart data for indicators
  const indicatorData = result ? {
    labels: ['Repetitive Patterns', 'Vocabulary Complexity', 'Sentence Structure', 'Coherence', 'Perplexity'],
    datasets: [{
      label: 'AI Indicators',
      data: [
        result.indicators.repetitivePatterns * 100,
        result.indicators.vocabularyComplexity * 100,
        result.indicators.sentenceStructure * 100,
        result.indicators.coherenceScore * 100,
        result.indicators.perplexityScore * 100
      ],
      backgroundColor: [
        'rgba(239, 68, 68, 0.8)',
        'rgba(245, 158, 11, 0.8)',
        'rgba(59, 130, 246, 0.8)',
        'rgba(16, 185, 129, 0.8)',
        'rgba(139, 92, 246, 0.8)'
      ],
      borderColor: [
        'rgba(239, 68, 68, 1)',
        'rgba(245, 158, 11, 1)',
        'rgba(59, 130, 246, 1)',
        'rgba(16, 185, 129, 1)',
        'rgba(139, 92, 246, 1)'
      ],
      borderWidth: 2
    }]
  } : null;

  // Doughnut chart for AI probability
  const probabilityData = result ? {
    labels: ['AI Generated', 'Human Written'],
    datasets: [{
      data: [result.aiProbability * 100, (1 - result.aiProbability) * 100],
      backgroundColor: [
        result.isAIGenerated ? 'rgba(239, 68, 68, 0.8)' : 'rgba(245, 158, 11, 0.8)',
        'rgba(16, 185, 129, 0.8)'
      ],
      borderColor: [
        result.isAIGenerated ? 'rgba(239, 68, 68, 1)' : 'rgba(245, 158, 11, 1)',
        'rgba(16, 185, 129, 1)'
      ],
      borderWidth: 2
    }]
  } : null;

  return (
    <div className="space-y-6">
      <div className="bg-white rounded-lg shadow-sm border p-6">
        <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center">
          <Bot className="w-6 h-6 mr-3 text-purple-600" />
          AI-Generated Content Detection
        </h2>
        
        <div className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Enter text to analyze for AI generation:
            </label>
            <textarea
              value={text}
              onChange={(e) => setText(e.target.value)}
              className="w-full h-40 p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent resize-none"
              placeholder="Paste your text here to check if it was generated by AI..."
            />
          </div>
          
          <div className="flex items-center justify-between">
            <div className="text-sm text-gray-500">
              {text.length} characters • {text.split(/\s+/).filter(w => w.length > 0).length} words
            </div>
            <button
              onClick={analyzeText}
              disabled={!text.trim() || isAnalyzing}
              className="px-6 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed flex items-center space-x-2"
            >
              {isAnalyzing ? (
                <>
                  <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
                  <span>Analyzing...</span>
                </>
              ) : (
                <>
                  <Brain className="w-4 h-4" />
                  <span>Analyze Text</span>
                </>
              )}
            </button>
          </div>
        </div>
      </div>

      {result && (
        <div className="space-y-6">
          {/* Main Result */}
          <div className={`rounded-lg p-6 border-2 ${getResultColor(result.isAIGenerated, result.confidence)}`}>
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center space-x-3">
                {getResultIcon(result.isAIGenerated)}
                <h3 className="text-xl font-bold">
                  {result.isAIGenerated ? 'AI-Generated Content Detected' : 'Human-Written Content'}
                </h3>
              </div>
              <div className="text-right">
                <div className="text-2xl font-bold">
                  {(result.aiProbability * 100).toFixed(1)}%
                </div>
                <div className="text-sm opacity-75">AI Probability</div>
              </div>
            </div>
            
            <p className="text-sm mb-4">{result.explanation}</p>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="flex justify-between">
                <span className="font-medium">Confidence Score:</span>
                <span>{(result.confidence * 100).toFixed(1)}%</span>
              </div>
              <div className="flex justify-between">
                <span className="font-medium">Detection Method:</span>
                <span>Multi-Algorithm Analysis</span>
              </div>
            </div>
          </div>

          {/* Detailed Analysis */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Indicators Chart */}
            <div className="bg-white rounded-lg shadow-sm border p-6">
              <h4 className="text-lg font-semibold text-gray-900 mb-4 flex items-center">
                <BarChart3 className="w-5 h-5 mr-2 text-blue-600" />
                AI Detection Indicators
              </h4>
              {indicatorData && (
                <Bar 
                  data={indicatorData} 
                  options={{
                    responsive: true,
                    plugins: {
                      legend: { display: false }
                    },
                    scales: {
                      y: {
                        beginAtZero: true,
                        max: 100,
                        ticks: {
                          callback: function(value) {
                            return value + '%';
                          }
                        }
                      },
                      x: {
                        ticks: {
                          maxRotation: 45,
                          minRotation: 45
                        }
                      }
                    }
                  }}
                />
              )}
            </div>

            {/* Probability Chart */}
            <div className="bg-white rounded-lg shadow-sm border p-6">
              <h4 className="text-lg font-semibold text-gray-900 mb-4 flex items-center">
                <FileText className="w-5 h-5 mr-2 text-green-600" />
                Content Origin Probability
              </h4>
              {probabilityData && (
                <Doughnut 
                  data={probabilityData}
                  options={{
                    responsive: true,
                    plugins: {
                      legend: {
                        position: 'bottom'
                      }
                    }
                  }}
                />
              )}
            </div>
          </div>

          {/* Detailed Metrics */}
          <div className="bg-white rounded-lg shadow-sm border p-6">
            <h4 className="text-lg font-semibold text-gray-900 mb-4">Detailed Analysis Metrics</h4>
            <div className="grid grid-cols-1 md:grid-cols-5 gap-4">
              <div className="text-center p-4 bg-red-50 rounded-lg">
                <div className="text-2xl font-bold text-red-600">
                  {(result.indicators.repetitivePatterns * 100).toFixed(1)}%
                </div>
                <div className="text-sm text-gray-600 mt-1">Repetitive Patterns</div>
                <div className="text-xs text-gray-500 mt-1">AI phrase usage</div>
              </div>
              
              <div className="text-center p-4 bg-orange-50 rounded-lg">
                <div className="text-2xl font-bold text-orange-600">
                  {(result.indicators.vocabularyComplexity * 100).toFixed(1)}%
                </div>
                <div className="text-sm text-gray-600 mt-1">Vocabulary</div>
                <div className="text-xs text-gray-500 mt-1">Formal word usage</div>
              </div>
              
              <div className="text-center p-4 bg-blue-50 rounded-lg">
                <div className="text-2xl font-bold text-blue-600">
                  {(result.indicators.sentenceStructure * 100).toFixed(1)}%
                </div>
                <div className="text-sm text-gray-600 mt-1">Structure</div>
                <div className="text-xs text-gray-500 mt-1">Sentence patterns</div>
              </div>
              
              <div className="text-center p-4 bg-green-50 rounded-lg">
                <div className="text-2xl font-bold text-green-600">
                  {(result.indicators.coherenceScore * 100).toFixed(1)}%
                </div>
                <div className="text-sm text-gray-600 mt-1">Coherence</div>
                <div className="text-xs text-gray-500 mt-1">Logical flow</div>
              </div>
              
              <div className="text-center p-4 bg-purple-50 rounded-lg">
                <div className="text-2xl font-bold text-purple-600">
                  {(result.indicators.perplexityScore * 100).toFixed(1)}%
                </div>
                <div className="text-sm text-gray-600 mt-1">Perplexity</div>
                <div className="text-xs text-gray-500 mt-1">Predictability</div>
              </div>
            </div>
          </div>

          {/* Recommendations */}
          <div className="bg-gradient-to-r from-purple-50 to-blue-50 rounded-lg p-6 border border-purple-200">
            <h4 className="font-semibold text-purple-900 mb-3">
              {result.isAIGenerated ? 'Recommendations for Human-like Writing:' : 'Content Authenticity Confirmed'}
            </h4>
            {result.isAIGenerated ? (
              <ul className="text-purple-800 text-sm space-y-1">
                <li>• Vary sentence lengths and structures more naturally</li>
                <li>• Use more conversational and less formal vocabulary</li>
                <li>• Add personal insights and unique perspectives</li>
                <li>• Include specific examples and anecdotes</li>
                <li>• Reduce overuse of transition words and formal phrases</li>
              </ul>
            ) : (
              <p className="text-green-800 text-sm">
                This content appears to be authentically human-written with natural language patterns and appropriate variation.
              </p>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

export default AIDetection;